module github.com/talif/aperture/backend

// The floor is the oldest Go this repository builds on, and it is set by the dependency
// rather than by anything the service needs: pgx v5.7.5 declares 1.23.
//
// Kept as low as the dependencies allow, deliberately. A declared version above the Go on
// a given machine forces a toolchain download, and that download is verified against the
// checksum database, so on a network that cannot reach sum.golang.org the whole thing is
// circular: the command that would fetch the dependency cannot run until it fetches a
// compiler it cannot verify.
//
// CI runs a newer Go, which is fine: a module declaring 1.23 builds with any later
// toolchain.
go 1.23.0

toolchain go1.24.7

// Pinned, deliberately.
//
// Shipping this unpinned let `go mod tidy` select the newest release, which required a
// language version this module does not declare, so Go rewrote the `go` directive and
// tried to upgrade its own toolchain to compensate. That is a large and invisible change
// to make on the strength of a `go get`, and it left go.mod claiming a version the machine
// could not satisfy.
//
// v5.7.5 is the newest release below the 1.25 language floor that v5.11 introduced.
//
// pgx over database/sql with lib/pq for two reasons that matter here: it speaks the
// PostgreSQL wire protocol natively, so the array and jsonb columns in the sync schema
// round-trip without manual encoding, and its pool exposes the lifetime controls needed to
// bound a slow query rather than let it exhaust the database's connection slots.
//
// go.sum is generated by `go mod tidy`; a module checksum cannot be written by hand.
require github.com/jackc/pgx/v5 v5.7.5

require (
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761 // indirect
	github.com/jackc/puddle/v2 v2.2.2 // indirect
	golang.org/x/crypto v0.37.0 // indirect
	golang.org/x/sync v0.13.0 // indirect
	golang.org/x/text v0.24.0 // indirect
)
